version: '3'
services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    build: ./mysql/
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mbtpy_db
    tty: true
  api:
    depends_on:
      - mysql
    container_name: api_from_compose
    platform: linux/x86_64
    build: ./api
    restart: always
    tty: true
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
    environment:
      - APP_SECRET_STRING=password
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - DATABASE=mbtpy_db
      - DATABASE_HOST=mysql